[package]
name = "mimosa"
version = "0.1.0"
authors = ["walker <warriorsfly@gmail.com>"]
edition = "2018"

[dependencies]
actix = "0.9.0"
actix-cors = "0.2.0"
actix-files = "0.2.1"
actix-identity = "0.2.1"
actix-redis = "0.8.1"
actix-rt = "1"
actix-service = "1.0.5"
actix-web = "2"
argon2rs = "0.2.5"
derive_more = "0.99.3"
dotenv = "0.15"
envy = "0.4"
env_logger = "0.7.1"
futures = "0.3.4"
jsonwebtoken = "7.1.0"
lazy_static = "1.4"
listenfd = "0.3"
log = "0.4.8"
rayon = "1.3.0"
redis-async = "0.6.2"
r2d2 = "0.8"
r2d2-diesel = "1.0.0"
serde = "1.0.104"
serde_derive = "1.0.104"
serde_json = "1.0.48"
uuid = { version = "0.8.1", features = ["serde", "v4"] }
validator = "0.10.0"
validator_derive = "0.10.0"

[dependencies.diesel]
version = "1.4.3"
features = ["chrono","mysql", "postgres", "sqlite", "r2d2", "uuidv07"]

[dependencies.chrono]
version = "0.4.11"
features = ["serde"]

[dev-dependencies]
actix-http-test = "1.0.0"

[features]
cockroach = []
mysql = []
postgres = []
sqlite = []
default = ["sqlite"]