[package]
name = "mimosa"
version = "0.1.0"
authors = ["walker <warriorsfly@gmail.com>"]
edition = "2018"

[dependencies]
actix = "0.10.0-alpha.3"
actix-cors = "0.3.0-alpha.1"
# actix-files = "0.2.1"
actix-identity = "0.3.0-alpha.1"
actix-redis = "0.9.0-alpha.2"
actix-rt = "1.1.1"
actix-service = "1.0.5"
argon2rs = "0.2.5"
# casbin = "0.4"
derive_more = "0.99.7"
dotenv = "0.15"
envy = "0.4"
env_logger = "0.7.1"
futures = "0.3.5"
jsonwebtoken = "7.1.0"
lazy_static = "1.4"
listenfd = "0.3"
log = "0.4.8"
rayon = "1.3.0"
redis-async = "0.6.3"
r2d2 = "0.8"
r2d2-diesel = "1.0.0"
serde = "1.0.111"
serde_derive = "1.0.111"
serde_json = "1.0.53"
uuid = { version = "0.8.1", features = ["serde", "v4"] }
validator = "0.10.0"
validator_derive = "0.10.0"

[dependencies.actix-web]
version = "3.0.0-alpha.3"
features = ["rustls"]

[dependencies.diesel]
version = "1.4.4"
features = ["chrono","mysql", "postgres", "sqlite", "r2d2", "uuid"]

[dependencies.chrono]
version = "0.4.11"
features = ["serde"]

[dev-dependencies]
actix-http-test = "1.0.0"

[features]
# mysql = []
postgres = []
# sqlite = []
default = ["postgres"]